name: Delete Pull Request Deployment
on:
  pull_request:
    branches: [ development, master ]
    types: [ closed ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: adam-site-${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        uses: b612-asteroid-institute/delete-repository-action@v1
        with:
          name: b612-asteroid-institute/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PAT }}