name: Production Build and Deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
#       - '.github/workflows/**'
      - '**.md'
env:
  URL: adam.b612.ai

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author 
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
          
      - name : machine ls build
        run : "ls -la build"
        
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'build/package.json'
        env:
          homepage: https://${{ env.URL }}
        
        
      - name: Build
        run: |
          cd build
          echo $(echo ${{ env.URL }} | tr '[:lower:]' '[:upper:]') > CNAME
          yarn install
          yarn run predeploy
      
      - name: Checkout Dev Target
        uses: actions/checkout@v2
        with:
          repository: b612-asteroid-institute/adam-site-prod
          path: 'deploy'
          token: ${{ secrets.PAT }}
      
      - name: Push files to target
        run: |
          cp -r build/build/* deploy
          cd deploy
          git add .
          git commit -m $GITHUB_SHA
          git push
