name: Pull Request Build and Deploy
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: adam-site-${{ github.event.pull_request.node_id }}
  REACT_APP_API_URL: https://precovery.api.b612.ai/

jobs:
  create-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Create new repository for temporary deployment
        uses: b612-asteroid-insitute/create-repository-action@v1
        with:
          name: ${{ env.PR_REPO_NAME }}
          # org: b612-asteroid-institute
          access-token: ${{ secrets.PAT }}
    
  pr-build-deploy:
    needs: create-page-host
    runs-on: ubuntu-latest
    environment: 
      name: pr-staging
      url: https://adam.b612.ai/${{ env.PR_REPO_NAME }}/
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'pr-build'
      
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'pr-build/package.json'
        env:
          homepage: https://adam.b612.ai/${{ env.PR_REPO_NAME }}

      - name: Build Pull Request
        run: |
          cd pr-build
          echo ${{ env.URL }} > CNAME
          yarn install
          yarn run predeploy
      
      - name: Checkout temporary deployment target repo
        uses: actions/checkout@v2
        with:
          repository: b612-asteroid-institute/${{ env.PR_REPO_NAME }}
          path: 'pr-deploy'
          token: ${{ secrets.PAT }}
      
      - name: Push files to target
        run: |
          cp -r pr-build/build/* pr-deploy
          cd pr-deploy
          git add .
          git commit -m $GITHUB_SHA
          git branch -M gh-pages
          git push -u origin gh-pages